// Polskie terminy ICNP 2017 — Diagnozy pielęgniarskie / Problemy pielęgniarskie
export const ICNP_DIAGNOZY = [
  // Ból
  'Ból ostry',
  'Ból przewlekły',
  'Ból pooperacyjny',
  'Ból nowotworowy',
  'Ból neuropatyczny',
  'Ból trzewny',
  'Ból mięśniowo-szkieletowy',
  // Zaburzenia oddychania
  'Duszność',
  'Nieefektywne oczyszczanie dróg oddechowych',
  'Zaburzenia wzorca oddychania',
  'Ryzyko aspiracji',
  'Hiperwentylacja',
  'Hipowentylacja',
  // Krążenie
  'Zaburzenia czynności układu krążenia',
  'Zaburzenia rytmu serca',
  'Hipotensja',
  'Nadciśnienie tętnicze',
  'Ryzyko powikłań zakrzepowych',
  'Ryzyko krwawienia',
  'Krwawienie',
  // Skóra / integralność
  'Zaburzenia integralności skóry',
  'Odleżyna — stadium I',
  'Odleżyna — stadium II',
  'Odleżyna — stadium III',
  'Odleżyna — stadium IV',
  'Ryzyko odleżyn',
  'Rana pooperacyjna',
  'Rana przewlekła',
  'Zakażenie rany',
  'Zaburzenia gojenia rany',
  // Ruchomość / aktywność
  'Upośledzona ruchomość fizyczna',
  'Nietolerancja aktywności',
  'Osłabienie',
  'Ryzyko upadku',
  'Upadek',
  'Dysfunkcja chodzenia',
  'Obniżona sprawność fizyczna',
  // Samoopieka
  'Deficyt samoopieki w zakresie higieny',
  'Deficyt samoopieki w zakresie żywienia',
  'Deficyt samoopieki w zakresie ubierania się',
  'Deficyt samoopieki w zakresie toalety',
  'Zaburzenia samoopieki',
  // Odżywianie
  'Ryzyko niedożywienia',
  'Niedożywienie',
  'Dysfagia',
  'Nudności',
  'Wymioty',
  'Zaburzenia odżywiania',
  'Utrata masy ciała',
  // Płyny / nawodnienie
  'Odwodnienie',
  'Przewodnienie',
  'Zaburzenia równowagi wodno-elektrolitowej',
  'Bilans płynów ujemny',
  // Wydalanie
  'Zaparcie',
  'Biegunka',
  'Zaburzenia czynności pęcherza moczowego',
  'Ostra retencja moczu',
  'Nietrzymanie moczu',
  'Stomia jelitowa — opieka',
  // Metabolizm / homeostaza
  'Hiperglikemia',
  'Hipoglikemia',
  'Hipertermia',
  'Hipotermia',
  'Gorączka',
  // Psychospołeczne / emocjonalne
  'Lęk',
  'Lęk przedoperacyjny',
  'Strach',
  'Bezsilność',
  'Beznadziejność',
  'Depresja',
  'Ryzyko samookaleczenia',
  'Ryzyko samobójstwa',
  'Pobudzenie',
  'Niepokój',
  'Zaburzenia samooceny',
  'Zaburzenia obrazu ciała',
  'Izolacja społeczna',
  'Zaburzenia relacji rodzinnych',
  'Nieefektywne radzenie sobie',
  // Poznawcze / świadomość
  'Dezorientacja',
  'Zaburzenia funkcji poznawczych',
  'Zaburzenia pamięci',
  'Zaburzenia świadomości',
  'Majaczenie',
  // Komunikacja
  'Zaburzenia komunikacji werbalnej',
  'Zaburzenia komunikacji',
  // Wiedza / edukacja
  'Niski poziom wiedzy — choroba',
  'Niski poziom wiedzy — farmakoterapia',
  'Niski poziom wiedzy — samopieka',
  'Niski poziom wiedzy — procedura',
  // Zakażenie
  'Ryzyko zakażenia',
  'Zakażenie',
  'Zakażenie układu moczowego',
  'Zakażenie dróg oddechowych',
  'Zakażenie miejsca operowanego',
  'Posocznica',
  // Sen
  'Zaburzenia snu',
  'Bezsenność',
  'Nadmierna senność',
  // Ból / komfort
  'Dyskomfort',
  'Nieefektywne zarządzanie bólem',
  'Ryzyko urazu',
  // Obrzęk
  'Obrzęk',
  'Obrzęk obwodowy',
  'Wodobrzusze',
];

// Polskie terminy ICNP 2017 — Interwencje pielęgniarskie
export const ICNP_INTERWENCJE = [
  // Ocena / monitoring
  'Ocena bólu',
  'Ocena bólu wg skali NRS',
  'Ocena bólu wg skali VAS',
  'Ocena bólu wg skali BPS',
  'Monitorowanie parametrów życiowych',
  'Pomiar ciśnienia tętniczego',
  'Pomiar temperatury ciała',
  'Pomiar tętna',
  'Pomiar saturacji (SpO₂)',
  'Pomiar glikemii',
  'Pomiar masy ciała',
  'Monitorowanie diurezy',
  'Bilans płynów',
  'Monitorowanie EKG',
  'Ocena stanu świadomości (GCS)',
  'Ocena ryzyka upadku',
  'Ocena ryzyka odleżyn wg skali Norton',
  'Ocena ryzyka odleżyn wg skali Braden',
  'Ocena stanu odżywienia (NRS-2002)',
  'Ocena skóry',
  'Ocena rany',
  'Ocena obrzęku',
  'Ocena stanu ogólnego pacjenta',
  'Ocena ryzyka zakażenia',
  // Farmakoterapia
  'Podawanie leków',
  'Podawanie leków drogą doustną',
  'Podawanie leków drogą dożylną',
  'Podawanie leków drogą domięśniową',
  'Podawanie leków drogą podskórną',
  'Podawanie leków drogą wziewną',
  'Podawanie leków drogą naskórną (plaster)',
  'Podawanie płynów dożylnych',
  'Monitorowanie skutków ubocznych leków',
  'Transfuzja krwi',
  'Podawanie insuliny',
  // Tlenoterapia / oddychanie
  'Tlenoterapia',
  'Podawanie tlenu przez kaniulę nosową',
  'Podawanie tlenu przez maskę',
  'Inhalacja',
  'Ćwiczenia oddechowe',
  'Fizjoterapia oddechowa',
  'Odsysanie wydzieliny z dróg oddechowych',
  'Pielęgnacja rurki tracheotomijnej',
  // Pielęgnacja skóry / ran
  'Pielęgnacja rany',
  'Zmiana opatrunku',
  'Zakładanie opatrunku',
  'Opatrunek rany pooperacyjnej',
  'Pielęgnacja rany przewlekłej',
  'Profilaktyka przeciwodleżynowa',
  'Zmiana pozycji ciała',
  'Materac przeciwodleżynowy — zastosowanie',
  'Pielęgnacja odleżyny',
  'Drenaż rany',
  'Usunięcie szwów/klamer',
  // Cewnikowanie / drenaż
  'Cewnikowanie pęcherza moczowego',
  'Pielęgnacja cewnika moczowego',
  'Usunięcie cewnika moczowego',
  'Pielęgnacja drenażu',
  // Dostęp naczyniowy
  'Zakładanie wkłucia obwodowego',
  'Pielęgnacja wkłucia dożylnego (obwodowego)',
  'Pielęgnacja wkłucia centralnego (CVC)',
  'Ocena miejsca wkłucia',
  // Żywienie
  'Żywienie doustne',
  'Żywienie przez sondę (NGT)',
  'Żywienie pozajelitowe',
  'Ocena stanu odżywienia',
  'Dieta — wdrożenie',
  'Nawadnianie doustne',
  // Higiena / samoopieka
  'Toaleta całego ciała',
  'Toaleta jamy ustnej',
  'Pielęgnacja oczu',
  'Pomoc w toalecie',
  'Pomoc przy ubieraniu się',
  'Pomoc przy spożywaniu posiłków',
  'Pielęgnacja krocza',
  // Stomia
  'Pielęgnacja stomii',
  'Wymiana worka stomijnego',
  // Rehabilitacja / aktywność
  'Rehabilitacja ruchowa',
  'Ćwiczenia bierne kończyn',
  'Ćwiczenia czynne kończyn',
  'Kinezyterapia',
  'Pionizacja pacjenta',
  'Nauka chodzenia',
  'Masaż leczniczy',
  'Zapobieganie przykurczom',
  // Edukacja
  'Edukacja pacjenta',
  'Edukacja rodziny / opiekuna',
  'Instruktaż samoopieki',
  'Edukacja dotycząca farmakoterapii',
  'Edukacja dotycząca diety',
  // Wsparcie psychologiczne
  'Wsparcie psychologiczne',
  'Komunikacja terapeutyczna',
  'Zmniejszanie lęku',
  'Motywowanie pacjenta',
  // Profilaktyka
  'Profilaktyka zakażeń',
  'Profilaktyka przeciwzakrzepowa',
  'Profilaktyka upadków',
  'Aseptyka i antyseptyka',
  // Procedury
  'Przygotowanie do zabiegu operacyjnego',
  'Opieka pooperacyjna',
  'Pobieranie materiału do badań (krew)',
  'Pobieranie materiału do badań (mocz)',
  'Pobieranie wymazu',
  'Przygotowanie do badania diagnostycznego',
  'Resuscytacja krążeniowo-oddechowa (RKO)',
  'Defibrylacja',
];
